// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6_D5666hHBnQqoBm6vjF6XVZhcDyfyY4',
    appId: '1:38607290109:android:3ef8d141fc16804717c894',
    messagingSenderId: '38607290109',
    projectId: 'mental-strength',
    storageBucket: 'mental-strength.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_ZS9AmYWRroqgUwQDhLTx4SHqZl7N7y4',
    appId: '1:38607290109:ios:f76a899a71e7322317c894',
    messagingSenderId: '38607290109',
    projectId: 'mental-strength',
    storageBucket: 'mental-strength.appspot.com',
    androidClientId: '38607290109-h93ue15kib3bguhgcvmqp00u9hr4mqtt.apps.googleusercontent.com',
    iosClientId: '38607290109-mudgmkhoghqg650lqprihoti6njui85p.apps.googleusercontent.com',
    iosBundleId: 'com.mentalhelth.mentalhelth',
  );

}